name: ci-cd

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    env:
      VERSION: "0.5.0-${{ github.run_number }}"
    outputs:
      VERSION: ${{ env.VERSION }}
      NAME: "gcd-dev"
    steps:
      - uses: actions/checkout@v4
        
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

  bin-build:
    uses: ./.github/workflows/ci-cd-bin-build.yml
    needs: build
    secrets: inherit
    with:
      version:  $env:VERSION
      
  bin-test:
    uses: ./.github/workflows/ci-cd-bin-test.yml
    needs: bin-build
    secrets: inherit

  nuget-build:
    uses: ./.github/workflows/ci-cd-nuget-build.yml
    needs: bin-test
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"

  nipkg-build:
    uses: ./.github/workflows/ci-cd-nipkg-build.yml
    needs: bin-test
    secrets: inherit
    with:
      version:  $env:VERSION
      name: gcd
    
  nipkg-publish:
    uses: ./.github/workflows/ci-cd-nipkg-publish.yml
    needs: nipkg-build
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
      name: gcd
      feed: ${{ vars.NIPK_DEV_FEED_READABLE }}
  

  nipkg-test:
    uses: ./.github/workflows/ci-cd-nipkg-test.yml
    needs: nipkg-publish
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
      name: gcd
      feed: ${{ vars.NIPK_DEV_FEED_READABLE }}
