name: ci-cd-nipkg-publish

on:
  workflow_call: # This allows this workflow to be called by other workflows

jobs:
  publish:
    runs-on: windows-latest
    env:
      VERSION: "0.5.0"

    steps:
    - name: download gcd bootstrap
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "gcd-bootstrap"

    - name: download gcd bootstrap
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-nipkg
        path: "package"

    - name: add to path
      run: |
        echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH
        
    - name: setup
      run: |
        gcd --version  
        gcd config set --nipkg-installer-uri  ${{secrets.NIPKGINSTALLERURI}}
        gcd config set --nipkg-cmd-path  "C:\\Program Files\\National Instruments\\NI Package Manager\\nipkg.exe"
        gcd tools install-nipkg

    - name: publish to feed
      run:  |
        gcd nipkg feed add-package-az `
        --package-path "$env:GITHUB_WORKSPACE\\package\\gcd_0.5.0-${{github.run_number}}_windows_x64.nipkg" `
        --feed-url "${{ secrets.NIPKG_DEV_FEED }}"



