name: ci-cd-nipkg-test

on:
  workflow_call:
    inputs:
      version:
        description: "package version"
        required: true
        type: string
      name:
        description: "package name"
        required: true
        type: string
      feed:
        description: "package feed"
        required: true
        type: string

jobs:
  test-end-to-end:
    runs-on: windows-latest
    steps:
      - name: download gcd 
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-bin
          path: gcd-bootstrap

      - name: download integration tests
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-test
          path: integration-tests 

      - name: add to path
        run: |
          echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH
          echo "C:\\Program Files\\National Instruments\\NI Package Manager" >> $env:GITHUB_PATH
         
      - name: setup
        env:
          NIPKGINSTALLERURI: ${{ secrets.NIPKGINSTALLERURI }}
          NIPKGCMDPATH: ${{ secrets.NIPKGCMDPATH }}
        run: |
          gcd --version  
          gcd config set --nipkg-installer-uri ${{env.NIPKGINSTALLERURI}}
          gcd config set --nipkg-cmd-path  "${{env.NIPKGCMDPATH}}"
          gcd tools install-nipkg
          nipkg -v
          nipkg feed-add "${{ inputs.feed}}" --name=gcd-dev --system
          nipkg list-installed
          nipkg feed-list
          nipkg list
          nipkg config-get
          nipkg update
          nipkg install gcd -y

      - name: app test
        env:
          AZUREADDPKGTESTFEEDURI: ${{ secrets.AZUREADDPKGTESTFEEDURI }}
          AZUREFEEDURI: ${{ secrets.AZUREFEEDURI }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.AZUREPUSHPULLTESTFEEDURI }}
          NipkgInstallerUri: ${{ secrets.NIPKGINSTALLERURI }}
          NipkgCmdPath: ${{ secrets.NIPKGCMDPATH }}
          DevMode : false
          GcdPath: "C:\\Program Files\\gcd\\gcd.exe"
        run: dotnet test  integration-tests/Gcd.Tests.EndToEnd.dll
