name: ci-cd-bin-test

on:
  workflow_call:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: download gcd 
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-bin
          path: gcd-bootstrap

      - name: download integration tests
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-test
          path: integration-tests

      - name: add to path
        run: |
          echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH
         
      - name: setup
        env:
          NIPKGINSTALLERURI: ${{ secrets.NIPKGINSTALLERURI }}
          NIPKGCMDPATH: ${{ secrets.NIPKGCMDPATH }}
        run: |
          gcd --version  
          gcd config set --nipkg-installer-uri ${{env.NIPKGINSTALLERURI}}
          gcd config set --nipkg-cmd-path  "${{env.NIPKGCMDPATH}}"
          gcd tools install-nipkg

      - name: dev test
        env:
          GITREPOADDRESS: ${{ secrets.test-git-repo }}
          GitUserName: ${{ secrets.test-git-user }}
          GitPassword: ${{ secrets.test-git-password }}  
          AZUREADDPKGTESTFEEDURI: ${{ secrets.test-feed-add-pkg }}
          AZUREFEEDURI: ${{ secrets.test-feed-generic }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.test-feed-push-pull }}
          NipkgInstallerUri: ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
          NipkgCmdPath: ${{vars.NIPKG_INSTALATION_DIR}}
          DevMode : true
        run: dotnet test  integration-tests/Gcd.Tests.EndToEnd.dll

      - name: app test
        env:
          GITREPOADDRESS: ${{ secrets.test-git-repo }}
          GitUserName: ${{ secrets.test-git-user }}
          GitPassword: ${{ secrets.test-git-password }}  
          AZUREADDPKGTESTFEEDURI: ${{ secrets.test-feed-add-pkg }}
          AZUREFEEDURI: ${{ secrets.test-feed-generic }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.test-feed-push-pull }}
          NipkgInstallerUri: ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
          NipkgCmdPath: ${{vars.NIPKG_INSTALATION_DIR}}
          DevMode : false
          GcdPath: ${{ github.workspace }}\gcd-bootstrap\gcd.exe
        run: dotnet test  integration-tests/Gcd.Tests.EndToEnd.dll