name: ci-cd-nuget-test

on:
  workflow_call: # This allows this workflow to be called by other workflows

jobs:
  test-end-to-end:
    runs-on: windows-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-test
          path: gcd-test

      - name: install gcd
        run: |
          dotnet nuget add source ${{secrets.nuget-feed}} --username "anyusername" --password  ${{ secrets.nuget-feed-key }}
          dotnet tool install --global gcd

      - name: setup
        env:
          NIPKG_CMD_PATH: "${{vars.NIPKG_INSTALATION_DIR}}\\nipkg.exe"
        run: |
          gcd --version  
          gcd config set --nipkg-installer-uri ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
          gcd config set --nipkg-cmd-path "${{env.NIPKG_CMD_PATH}}"
          gcd tools install-nipkg
          Get-Command gcd

      - name: app test 
        env:
          SmbShareAddress: ${{ secrets.test-smb-share }}
          SmbUserName: ${{ secrets.test-smb-user }}
          SmbUserPass: ${{ secrets.test-smb-password }}  
          GitRepoAddress: ${{ secrets.test-git-repo }}
          GitUserName: ${{ secrets.test-git-user }}
          GitPassword: ${{ secrets.test-git-password }}  
          AZUREADDPKGTESTFEEDURI: ${{ secrets.test-feed-add-pkg }}
          AZUREFEEDURI: ${{ secrets.test-feed-generic }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.test-feed-push-pull }}
          NipkgInstallerUri: ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
          NipkgCmdPath: "${{vars.NIPKG_INSTALATION_DIR}}\\nipkg.exe"
          DevMode : false
          GcdPath: "C:\\Users\\runneradmin\\.dotnet\\tools\\gcd.exe"
        run: dotnet test gcd-test/Gcd.Tests.EndToEnd.dll

