name: ci-cd-nipkg-build

on:
  workflow_call: # This allows this workflow to be called by other workflows
    inputs:
      version:
        description: "package version"
        required: true
        type: string
      name:
        description: "package name"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: download gcd bootstrap
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "gcd-bootstrap"

    - name: download gcd bin
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "package-content"

    - name: add to path
      run: |
        echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH
        echo "C:\\Program Files\\National Instruments\\NI Package Manager" >> $env:GITHUB_PATH
        
    - name: setup
      run: |
        gcd --version  
        gcd tools install-nipkg --installer-source-uri ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
        nipkg update
        nipkg upgrade --force-locked --yes --accept-eulas --verbose system-windows-x64 ni-msiproperties eula-ms-dotnet-4.8 ni-msdotnet4x ni-package-manager-deployment-support
        nipkg install --force-locked --yes --accept-eulas --verbose --allow-downgrade --allow-uninstall ni-package-manager=20.0.0.49153-0+f1

    - name: build nipkg
      env:
        PACKAGE_OUTPUT_DIR: ${{github.workspace}}\package
        MANIFEST_DIR: ${{github.workspace}}\manifests\nipkg
      run:  |
        mkdir ${{env.PACKAGE_OUTPUT_DIR}}
        gcd nipkg build `
        --content-src-dir ${{github.workspace}}\package-content `
        --target-root-dir "BootVolume/Program Files/gcd" `
        --instructions-file-path ${{env.MANIFEST_DIR}}\instructions `
        --control-file-path ${{env.MANIFEST_DIR}}\control `
        --package-name ${{inputs.name}}  `
        --package-version ${{inputs.version}} `
        --package-destination-dir  ${{env.PACKAGE_OUTPUT_DIR}}

    - name: upload package artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: gcd-nipkg
        path: "package"



