name: cicd

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      VERSION: "0.5.0"

  bin-build:
    uses: ./.github/workflows/ci-cd-bin-build.yml
    needs: build
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
        
  test-end-to-end:
    uses: ./.github/workflows/ci-cd-test.yml
    needs: build
    secrets: inherit

  nipkg-build:
    uses: ./.github/workflows/ci-cd-nipkg-build.yml
    needs: test-end-to-end
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
      name: gcd
    
  nipkg-publish:
    uses: ./.github/workflows/ci-cd-nipkg-publish.yml
    needs: nipkg-build
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
      name: gcd
      feed: ${{ vars.NIPK_DEV_FEED_READABLE }}
  

  nipkg-test:
    uses: ./.github/workflows/ci-cd-nipkg-test.yml
    needs: nipkg-publish
    secrets: inherit
    with:
      version: "0.5.0-${{github.run_number}}"
      name: gcd
      feed: ${{ vars.NIPK_DEV_FEED_READABLE }}
