name: ci-cd-test-integration

on:
  workflow_call:

jobs:
  test-end-to-end:
    runs-on: windows-latest
    steps:
      - name: download gcd 
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-bin
          path: gcd-bootstrap

      - name: download integration tests
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-integration-tests
          path: integration-tests 

      - name: add gcd to path
        run: |
          echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH

      - name: setup gcd
        env:
          NIPKGINSTALLERURI: ${{ secrets.NIPKGINSTALLERURI }}
          NIPKGCMDPATH: ${{ secrets.NIPKGCMDPATH }}
        run: |
          gcd --version  
          gcd config set --nipkg-installer-uri ${{env.NIPKGINSTALLERURI}}
          gcd config set --nipkg-cmd-path  "${{env.NIPKGCMDPATH}}"

      - name: install nipkg
        run: |
          gcd tools install-nipkg
        working-directory: ./gcd-bootstrap

      - name: dev test
        env:
          AZUREADDPKGTESTFEEDURI: ${{ secrets.AZUREADDPKGTESTFEEDURI }}
          AZUREFEEDURI: ${{ secrets.AZUREFEEDURI }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.AZUREPUSHPULLTESTFEEDURI }}
          NipkgInstallerUri: ${{ secrets.NIPKGINSTALLERURI }}
          NipkgCmdPath: ${{ secrets.NIPKGCMDPATH }}
          DevMode : true
        run: dotnet test  integration-tests/Gcd.Tests.EndToEnd.dll

      - name: app test
        env:
          AZUREADDPKGTESTFEEDURI: ${{ secrets.AZUREADDPKGTESTFEEDURI }}
          AZUREFEEDURI: ${{ secrets.AZUREFEEDURI }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.AZUREPUSHPULLTESTFEEDURI }}
          NipkgInstallerUri: ${{ secrets.NIPKGINSTALLERURI }}
          NipkgCmdPath: ${{ secrets.NIPKGCMDPATH }}
          DevMode : false
          GcdPath: ${{ github.workspace }}\gcd-bootstrap\gcd.exe
        run: dotnet test  integration-tests/Gcd.Tests.EndToEnd.dll
