name: ci-cd-nuget-test

on:
  workflow_call: # This allows this workflow to be called by other workflows
    inputs:
      version:
        required: true
        type: string

jobs:
  test-end-to-end:
    runs-on: windows-latest
    steps:
      - name: download tests
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-test
          path: gcd-test

      - name: install gcd
        run: |
          dotnet nuget add source ${{secrets.nuget-feed}} --username "anyusername" --password  ${{ secrets.nuget-feed-key }}
          dotnet tool install --global Versionize
          dotnet tool install --global gcd --version ${{ inputs.version }} --verbosity detailed

      - name: add to path
        run: |
              echo "${{vars.NIPKG_INSTALATION_DIR}}" >> $env:GITHUB_PATH

      - name: setup
        run: |
          gcd --version  
          gcd tools install-nipkg --installer-source-uri ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}

      - name: app test 
        env:
          SmbShareAddress: ${{ secrets.test-smb-share }}
          SmbUserName: ${{ secrets.test-smb-user }}
          SmbUserPass: ${{ secrets.test-smb-password }}  
          GitRepoAddress: ${{ secrets.test-git-repo }}
          GitUserName: ${{ secrets.test-git-user }}
          GitPassword: ${{ secrets.test-git-password }}  
          AZUREADDPKGTESTFEEDURI: ${{ secrets.test-feed-add-pkg }}
          AZUREFEEDURI: ${{ secrets.test-feed-generic }}
          AZUREPUSHPULLTESTFEEDURI: ${{ secrets.test-feed-push-pull }}
          NipkgInstallerUri: ${{vars.NIPKGI_NSTALLER_DOWNLOAD_URI}}
          NipkgCmdPath: "${{vars.NIPKG_INSTALATION_DIR}}\\nipkg.exe"
          DevMode : false
          GcdPath: "C:\\Users\\runneradmin\\.dotnet\\tools\\gcd.exe"
        run: dotnet test gcd-test/Gcd.Tests.EndToEnd.dll

