name: dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  setup:
    if: ${{ github.actor != 'github-actions[bot]'}} 
    runs-on: windows-latest
    outputs:
      VERSION: ${{ steps.versionize.outputs.version }}.${{ github.run_number}}
      NAME: "gcd-dev"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          
      - name: install versionize
        run: dotnet tool install --global Versionize

      - name: setup git
        run: |
          git config --local user.email "dawid.wozny@zoryatec.com"
          git config --local user.name "github-actions[bot]"

      - name: Run versionize and debug output
        id: versionize
        run: |
          VERSION=$(versionize inspect)
          echo "VERSION is: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
  
      - name: Debug environment variable
        run: |
          echo "Captured VERSION from env: $VERSION"
        env:
          VERSION: ${{ env.version }}

      - name: Debug output value
        run: |
          echo "Captured VERSION from step output: ${{ steps.versionize.outputs.version }}"

     
  ci-cd:
    uses: ./.github/workflows/ci-cd.yml
    needs: setup
    secrets: inherit
    with:
      version: ${{needs.setup.outputs.VERSION}}
      name: ${{needs.setup.outputs.NAME}}
      nuget-feed: ""
      nipkg-feed: ${{vars.NIPK_DEV_FEED_READABLE}}
