name: dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  setup:
    runs-on: windows-latest
    outputs:
      VERSION: ${{ env.VERSION }}
      NAME: "gcd-dev"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          
      - name: install versionize
        run: dotnet tool install --global Versionize

      - name: setup git
        run: |
          git config --local user.email "dawid.wozny@zoryatec.com"
          git config --local user.name "github-actions[bot]"

      - name: output version
        id: versionize
        run: |
          $VERSION = versionize inspect
          Write-Host "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        continue-on-error: true

      - name: Use version in next steps
        run: |
          echo "The version is ${{ env.VERSION }}"


    
        
  ci-cd:
    uses: ./.github/workflows/ci-cd.yml
    needs: setup
    secrets: inherit
    with:
      version: ${{needs.setup.outputs.VERSION}}
      name: ${{needs.setup.outputs.NAME}}
      nuget-feed: ""
      nipkg-feed: ${{vars.NIPK_DEV_FEED_READABLE}}
