# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Run PowerShell script
      shell: pwsh  
      run: |
        ./install-nipkg.ps1

    - name: Wait for x seconds (Windows)
      shell: pwsh  # PowerShell shell
      run: |
        Write-Host "Waiting for 30 seconds..."
        Start-Sleep -Seconds 360  # PowerShell sleep for 360 seconds
      
    - name: Check dir
      run: dir "C:\Program Files\National Instruments\NI Package Manager"
      
    - name: Make PATH change permanent (for subsequent steps)
      shell: pwsh
      run: |
        # Define the path to add
        $newPath = "C:\Program Files\National Instruments\NI Package Manager"
        
        # Add the new path to the user-level PATH variable
        [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::User)
  
        # Optionally verify the update
        Write-Host "User-level PATH updated: $env:PATH"

    - name: Run Command from New PATH Directory
      shell: pwsh
      run: |
        # Running a command that should now work with the new PATH
        Write-Host "Running a command from the new PATH"
        # For example, checking the version of a tool in C:\tools
        if (Test-Path "$newPath\nipkg.exe") {
          & "$newPath\nipkg.exe" --version
        } else {
          Write-Host "Executable not found!"
        }

    - name: Check NIPKG version
      run: nipkg --version
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build src/Gcd/Gcd.csproj  --no-restore
      
    - name: Publish
      run:  dotnet publish src/Gcd/Gcd.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output ./publish

    - name: Upload Published Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gcd-published-artifacts
        path: ./publish  # Path to the published output directory
