name: Run End-to-End Tests in Docker

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull dawidwozny/labview:23.3.6_x86

      - name: Build Docker image
        run: docker build -t gcd-e2e-labview-test .

      - name: Run tests in Docker
        run: docker run --rm gcd-e2e-labview-test