name: Run End-to-End Tests in Docker

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t gcd-e2e-labview-test .

      - name: Run tests in Docker
        run: docker run --rm gcd-e2e-labview-test