name: Publish to NIPKG

on:
  workflow_call: # This allows this workflow to be called by other workflows

jobs:
  publish:
    runs-on: windows-latest
    env:
      VERSION: "0.5.0"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download gcd binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "./gcd-bootstrap"

    - name: Add GCD to path
      run: |
        echo "$env:GITHUB_WORKSPACE\\gcd-bootstrap" >> $env:GITHUB_PATH

    - name: Download gcd binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "./package-content"
        
    - name: Download gcd binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: gcd-bin
        path: "./package/data/BootVolume/Program Files/gcd"

    - name: Setup gcd
      run: |
        gcd --version  
        gcd config set --nipkg-installer-uri  "https://download.ni.com/support/nipkg/products/ni-package-manager/installers/NIPackageManager21.3.0_online.exe"
        gcd config set --nipkg-cmd-path  "C:\\Program Files\\National Instruments\\NI Package Manager\\nipkg.exe"
        
    - name: Install NIPKG
      run: |
        gcd nipkg install-nipkg             
        
    - name: Build NIPKG package
      run:  |
        gcd nipkg package create `
        --package-sourec-dir "package-content" `
        --package-name "gcd" `
        --package-version "0.5.0-${{github.run_number}}" `
        --package-instalation-dir "BootVolume/Program Files/gcd" `
        --package-destination-dir "package"

    - name: Upload package
      uses: actions/upload-artifact@v4.4.3
      with:
        name: gcd-pckg-temp
        path: "D:\\a\\gcd\\gcd\\package"
        
    - name: Copy package
      run:  |
        mkdir "D:\\a\\gcd\\gcd\\tempFeed"
        copy "D:\\a\\gcd\\gcd\\package\\gcd_0.5.0-${{github.run_number}}_windows_x64.nipkg" "D:\\a\\gcd\\gcd\\tempFeed\\gcd_0.5.0-${{github.run_number}}_windows_x64.nipkg"

    - name: Publish NIPKG package
      run:  |
        gcd nipkg add-package-blob-feed `
        --package-path "D:\\a\\gcd\\gcd\\package\\gcd_0.5.0-${{github.run_number}}_windows_x64.nipkg" `
        --feed-url "https://zoryatecartifacts.blob.core.windows.net/gcd-feed?${{ secrets.SAS_TOKEN }}"
        
    - name: Upload feed
      uses: actions/upload-artifact@v4.4.3
      with:
        name: gcd-feed-temp
        path: "D:\\a\\gcd\\gcd\\tempFeed"



