name: 'release'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    outputs:
      VERSION: ${{ steps.versionize.outputs.version }}
      TAG: v${{ steps.versionize.outputs.version }}
      NAME: "gcd"
    if: ${{ github.actor != 'github-actions[bot]' && github.ref == 'refs/heads/main' }} 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Setup git
        run: |
          git config --local user.email "dawid.wozny@zoryatec.com"
          git config --local user.name "github-actions[bot]"

      - name: Versionize Release
        id: versionize
        run: versionize --exit-insignificant-commits
        continue-on-error: true

      - name: No release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping publishing. No release required."

      - name: Build Package
        if: steps.versionize.outcome == 'success'
        run: dotnet pack src/Gcd/Gcd.csproj --output nupkgs --configuration Release
      # - name: Push to Nuget
      #   if: steps.versionize.outcome == 'success'
      #   run: dotnet nuget push "nupkgs\*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Run versionize and debug output
        id: versionize2
        run: |
          VERSION=$(versionize inspect)
          echo "VERSION is: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
    
      - name: Debug environment variable
        run: |
          echo "Captured VERSION from env: $VERSION"
        env:
          VERSION: ${{ env.version }}

      - name: Debug output value
        run: |
          echo "Captured VERSION from step output: ${{ steps.versionize2.outputs.version }}"

      
  release:
    uses: ./.github/workflows/ci-cd.yml
    needs: setup
    with:
      version: ${{needs.setup.outputs.VERSION}}
      name: ${{needs.setup.outputs.NAME}}
    secrets:
      nipkg-feed: ${{secrets.NIPKG_PROD_FEED}}
      nipkg-feed-sas: ${{secrets.NIPKG_PROD_FEED_SAS}}
      test-feed-add-pkg: ${{ secrets.AZUREADDPKGTESTFEEDURI }}
      test-feed-push-pull: ${{ secrets.AZUREPUSHPULLTESTFEEDURI }}
      test-feed-generic: ${{ secrets.AZUREFEEDURI }}
      nuget-feed: ${{ secrets.NUGET_DEV_FEED  }} # dev for now
      nuget-feed-key: ${{ secrets.GITHUB_TOKEN}}

  release-gh:
    uses: ./.github/workflows/release-gh.yml
    needs: setup
    with:
      tag: "v0.4.0"
