name: 'release-nuget'

on:
  workflow_dispatch:
    inputs:
        version :
          description: "Version of package to be tested"
          default: "0.1.0"

jobs:
  publish-new-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: install gcd
        run: |
            dotnet tool install --global gcd --version ${{ github.event.inputs.version }}

      - name: setup gcd
        run: |
            gcd --version  
            gcd config set --nipkg-installer-uri "https://download.ni.com/support/nipkg/products/ni-package-manager/installers/NIPackageManager21.3.0_online.exe"
            gcd config set --nipkg-cmd-path  "C:\\Program Files\\National Instruments\\NI Package Manager\\nipkg.exe"
            gcd tools install-nipkg
            gcd --version  
