name: Integration Test Stage

on:
  workflow_call: # This allows this workflow to be called by other workflows

jobs:
  test-end-to-end:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download gcd for bootstraping
        uses: actions/download-artifact@v4.1.8
        with:
          name: gcd-bin
          path: "./gcd-bootstrap"

      - name: Setup gcd
        run: |
          .\gcd.exe --version  
          .\gcd.exe config set --nipkg-installer-uri  "https://download.ni.com/support/nipkg/products/ni-package-manager/installers/NIPackageManager21.3.0_online.exe"
          .\gcd.exe config get --nipkg-installer-uri
          .\gcd.exe config set --nipkg-cmd-path  "C:\\Program Files\\National Instruments\\NI Package Manager\\nipkg.exe"
          .\gcd.exe config get --nipkg-cmd-path
          .\gcd.exe tools add-to-user-path "{{env.GITHUB_WORKSPACE}}\\gcd-bootstrap"
        working-directory: ./gcd-bootstrap

      - name: Install NIPKG
        run: |
          .\gcd.exe nipkg install-nipkg
        working-directory: ./gcd-bootstrap

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src/Gcd/Gcd.csproj  --no-restore

      - name: Test
        run: dotnet test tests/Gcd.Tests.EndToEnd/Gcd.Tests.EndToEnd.csproj
